canton {
  parameters {
    non-standard-config = yes
  }

  sequencers {
    sequencer1 {
      storage {
        type = postgres
        config {
          dataSourceClass = "org.postgresql.ds.PGSimpleDataSource"
          properties = {
            serverName = "canton-postgres"
            portNumber = 5432
            databaseName = "canton"
            user = "canton"
            password = "canton"
          }
        }
      }
      sequencer {
        type = reference
      }
      public-api {
        port = 6001
      }
      admin-api {
        port = 6002
      }
    }
  }

  mediators {
    mediator1 {
      storage {
        type = postgres
        config {
          dataSourceClass = "org.postgresql.ds.PGSimpleDataSource"
          properties = {
            serverName = "canton-postgres"
            portNumber = 5432
            databaseName = "canton"
            user = "canton"
            password = "canton"
          }
        }
      }
      admin-api {
        port = 7002
      }
    }
  }

  participants {
    participant1 {
      storage {
        type = postgres
        config {
          dataSourceClass = "org.postgresql.ds.PGSimpleDataSource"
          properties = {
            serverName = "canton-postgres"
            portNumber = 5432
            databaseName = "canton"
            user = "canton"
            password = "canton"
          }
        }
      }
      ledger-api {
        port = 4001
      }
      admin-api {
        port = 5002
      }
      http-ledger-api {
        server {
          port = 4001
        }
      }
    }
  }
}
